name: Build and Run FastAPI Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t vartika1910/fastapi-app:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 vartika1910/fastapi-app:latest

      - name: Test FastAPI service
        run: |
          curl --fail http://localhost:5000/

      - name: Stop and remove Docker container
        run: |
          docker ps -q --filter "ancestor=vartika1910/your-fastapi-app:latest" | xargs -r docker stop
          docker ps -a -q --filter "ancestor=vartika1910/your-fastapi-app:latest" | xargs -r docker rm
