name: Deploy FastAPI with Docker                     

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run Docker container
        run: |
          docker run -d -p 5002:5000 fastapi-app
