name: Deploy FastAPI with Docker

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python 3.12 from PATH
        run: |
          python --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: self-hosted
    needs: test 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 fastapi-app

          # name: Run FastAPI Locally on PR Merge