name: Run FastAPI Locally on PR Merge
on:
  pull_request:
    types: [closed]
    branches:
      - main
 
jobs:
  run_locally:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Use Python 3.12 from PATH
        run: |
          python --version
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
 
      - name: Start FastAPI server
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 5000 --reload