name: Run FastAPI Locally on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run_locally:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 --reload

      - name: Wait for FastAPI server to be up
        run: |
          timeout /t 2
